In [1]:
import numpy as np

## NumPy Array Creation Functions

### 1. `np.linspace()`: Create an array with evenly spaced numbers over a specified interval.

In [17]:
# Create 5 evenly spaced numbers from 0 to 10
linspace_array = np.linspace(0, 10, 5)
print("linspace_array:", linspace_array)

linspace_array: [ 0.   2.5  5.   7.5 10. ]


### 2. `np.logspace()`: Create an array with numbers that are evenly spaced on a log scale.

In [18]:
# Create 5 evenly spaced numbers on a log scale from 10^0 to 10^2
logspace_array = np.logspace(0, 2, 5)
print("logspace_array:", logspace_array)

logspace_array: [  1.           3.16227766  10.          31.6227766  100.        ]


### 3. `np.full()`: Create an array of a given shape and fill it with a specified value.

In [19]:
# Create a 2x3 array filled with 7s
full_array = np.full((2, 3), 7)
print("full_array:\n", full_array)

full_array:
 [[7 7 7]
 [7 7 7]]


### 4. `np.eye()`: Create a 2-D array with ones on the diagonal and zeros elsewhere (identity matrix).

In [20]:
# Create a 3x3 identity matrix
eye_array = np.eye(3)
print("eye_array:\n", eye_array)

eye_array:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 5. `np.identity()`: Create a square identity matrix.

In [21]:
# Create a 4x4 identity matrix
identity_array = np.identity(4)
print("identity_array:\n", identity_array)

identity_array:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Random Arrays

### 1. Vectors (1D Arrays)

In [7]:
# Create a 1D array (vector) of 5 random numbers between 0 and 1
random_vector = np.random.rand(5)
print("random_vector:", random_vector)

random_vector: [0.1650404  0.73468297 0.48596049 0.37760707 0.10338453]


### 2. Matrices (2D Arrays)

In [8]:
# Create a 2x3 matrix of random numbers
random_matrix = np.random.rand(2, 3)
print("random_matrix:\n", random_matrix)

random_matrix:
 [[0.3645265  0.48546816 0.08619709]
 [0.19476457 0.70660534 0.13945867]]


### 3. 3D Arrays

In [9]:
# Create a 2x2x2 3D array of random integers between 0 and 9
random_3d_array = np.random.randint(0, 10, size=(2, 2, 2))
print("random_3d_array:\n", random_3d_array)

random_3d_array:
 [[[2 9]
  [6 3]]

 [[7 4]
  [0 4]]]


## NumPy Array Attributes

In [10]:
# Let's use this array for demonstrating attributes
example_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Example Array:\n", example_array)

Example Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### 1. `shape`: The dimensions of the array as a tuple.

In [11]:
print("Shape of example_array:", example_array.shape)

Shape of example_array: (2, 2, 2)


### 2. `ndim`: The number of dimensions of the array.

In [12]:
print("Number of dimensions (ndim) of example_array:", example_array.ndim)

Number of dimensions (ndim) of example_array: 3


### 3. `size`: The total number of elements in the array.

In [13]:
print("Total number of elements (size) in example_array:", example_array.size)

Total number of elements (size) in example_array: 8


### 4. `dtype`: The data type of the elements in the array.

In [14]:
print("Data type (dtype) of elements in example_array:", example_array.dtype)

Data type (dtype) of elements in example_array: int64


### 5. `itemsize`: The size in bytes of each element of the array.

In [15]:
print("Size in bytes of each element (itemsize) in example_array:", example_array.itemsize)

Size in bytes of each element (itemsize) in example_array: 8


### 6. `nbytes`: The total number of bytes consumed by the array data.

In [16]:
print("Total bytes consumed by array data (nbytes) in example_array:", example_array.nbytes)

Total bytes consumed by array data (nbytes) in example_array: 64
