In [6]:
import numpy as np

# Create a sample NumPy array
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16],
    [17, 18, 19, 20]
])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


### Positive Indexing

In [7]:
# Select the first row
print(arr[0])

# Select element at row index 2, column index 1
print(arr[2, 1])

[1 2 3 4]
10


### Negative Indexing

In [8]:
# Select the last row
print(arr[-1])

# Select element at last row, second to last column
print(arr[-1, -2])

[17 18 19 20]
19


### Slicing

In [9]:
# Slice rows (rows 0 to 2, exclusive of 3)
print(arr[0:3])

# Slice columns (columns 1 to 2, exclusive of 3)
print(arr[:, 1:3])

# Slice rows and columns
print(arr[1:4, 0:2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]]
[[ 5  6]
 [ 9 10]
 [13 14]]


### Multi-dimensional Indexing and Selecting Rows/Columns

In [10]:
# Select specific rows (row 0 and row 2)
print(arr[[0, 2]])

# Select specific columns (column 0 and column 2)
print(arr[:, [0, 2]])

# Select elements based on a condition (multi-dimensional)
print(arr[arr[:, 0] > 5])

# Select a single row
print(arr[1])

# Select a single column
print(arr[:, 2])

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]
[[ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[5 6 7 8]
[ 3  7 11 15 19]


## Array Manipulation Functions (NumPy)

In [11]:
import numpy as np

# Original array for manipulation
original_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original array:")
print(original_arr)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### `reshape()`

In [12]:
# Reshape to 1D array
reshaped_1d = original_arr.reshape(9)
print("Reshaped to 1D (9 elements):")
print(reshaped_1d)

# Reshape to 3x3 array (already is, but demonstrates)
reshaped_3x3 = original_arr.reshape(3, 3)
print("Reshaped to 3x3:")
print(reshaped_3x3)

# Reshape to 9x1 array
reshaped_9x1 = original_arr.reshape(9, 1)
print("Reshaped to 9x1:")
print(reshaped_9x1)

# Reshape to 1x9 array
reshaped_1x9 = original_arr.reshape(1, 9)
print("Reshaped to 1x9:")
print(reshaped_1x9)

# Reshape using -1 for one dimension (NumPy infers size)
reshaped_2x_neg1 = original_arr.reshape(3, -1)
print("Reshaped to 3x-1 (3 rows, inferred columns):")
print(reshaped_2x_neg1)

Reshaped to 1D (9 elements):
[1 2 3 4 5 6 7 8 9]
Reshaped to 3x3:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped to 9x1:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
Reshaped to 1x9:
[[1 2 3 4 5 6 7 8 9]]
Reshaped to 3x-1 (3 rows, inferred columns):
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### `flatten()`

In [13]:
# Flatten the array
flattened_arr = original_arr.flatten()
print("Flattened array:")
print(flattened_arr)

# Flatten creates a copy, so modifying it doesn't affect original
flattened_arr[0] = 99
print("Modified flattened array:")
print(flattened_arr)
print("Original array (unaffected):")
print(original_arr)

Flattened array:
[1 2 3 4 5 6 7 8 9]
Modified flattened array:
[99  2  3  4  5  6  7  8  9]
Original array (unaffected):
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### `ravel()`

In [14]:
# Ravel the array
raveled_arr = original_arr.ravel()
print("Raveled array:")
print(raveled_arr)

# Ravel returns a view if possible (or copy if necessary). Modifying it *can* affect original.
raveled_arr[0] = 100
print("Modified raveled array:")
print(raveled_arr)
print("Original array (potentially affected):")
print(original_arr)

# Reset original array for next demos
original_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

Raveled array:
[1 2 3 4 5 6 7 8 9]
Modified raveled array:
[100   2   3   4   5   6   7   8   9]
Original array (potentially affected):
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


### `transpose()`

In [15]:
# Transpose the array
transposed_arr = original_arr.transpose()
print("Transposed array:")
print(transposed_arr)

# Using .T attribute (shorthand for transpose)
transposed_T = original_arr.T
print("Transposed using .T attribute:")
print(transposed_T)

Transposed array:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Transposed using .T attribute:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### `resize()`

In [16]:
# Create a new array for resize demo, as resize modifies in-place
resize_arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array for resize:")
print(resize_arr)

# Resize to a larger shape (pads with zeros)
resize_arr.resize((3, 3))
print("Resized to larger (3x3):")
print(resize_arr)

# Resize to a smaller shape (truncates)
resize_arr.resize((2, 2))
print("Resized to smaller (2x2):")
print(resize_arr)

Original array for resize:
[[1 2 3]
 [4 5 6]]
Resized to larger (3x3):
[[1 2 3]
 [4 5 6]
 [0 0 0]]
Resized to smaller (2x2):
[[1 2]
 [3 4]]


## Broadcasting Rules, Scalar Operations, and Array Compatibility (NumPy)

In [17]:
import numpy as np

print("Original arrays for broadcasting/scalar operations:")
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])
arr3 = np.array([[100], [200]])
arr4 = np.array([7])
print("arr1 (2x3):")
print(arr1)
print("arr2 (1x3):")
print(arr2)
print("arr3 (2x1):")
print(arr3)
print("arr4 (scalar-like):")
print(arr4)

Original arrays for broadcasting/scalar operations:
arr1 (2x3):
[[1 2 3]
 [4 5 6]]
arr2 (1x3):
[10 20 30]
arr3 (2x1):
[[100]
 [200]]
arr4 (scalar-like):
[7]


### Scalar Operations

In [18]:
# Adding a scalar to an array
result_scalar_add = arr1 + 5
print("arr1 + 5:")
print(result_scalar_add)

# Multiplying an array by a scalar
result_scalar_mul = arr1 * 2
print("arr1 * 2:")
print(result_scalar_mul)

# Subtracting a scalar from an array
result_scalar_sub = arr1 - 1
print("arr1 - 1:")
print(result_scalar_sub)

# Dividing an array by a scalar
result_scalar_div = arr1 / 2
print("arr1 / 2:")
print(result_scalar_div)

arr1 + 5:
[[ 6  7  8]
 [ 9 10 11]]
arr1 * 2:
[[ 2  4  6]
 [ 8 10 12]]
arr1 - 1:
[[0 1 2]
 [3 4 5]]
arr1 / 2:
[[0.5 1.  1.5]
 [2.  2.5 3. ]]


### Broadcasting Rules

In [19]:
# Example 1: Add a 1D array (arr2) to a 2D array (arr1)
# arr1 shape: (2, 3)
# arr2 shape: (3,)
# Rule: arr2 is broadcasted across the rows of arr1
result_broadcast_1 = arr1 + arr2
print("arr1 + arr2:")
print(result_broadcast_1)

# Example 2: Add a 2D array (arr3) with shape (2,1) to arr1 (2,3)
# arr1 shape: (2, 3)
# arr3 shape: (2, 1)
# Rule: arr3 is broadcasted across the columns of arr1
result_broadcast_2 = arr1 + arr3
print("arr1 + arr3:")
print(result_broadcast_2)

# Example 3: Add a scalar-like array (arr4) to arr1 (2,3)
# arr1 shape: (2, 3)
# arr4 shape: (1,)
# Rule: arr4 is broadcasted to match arr1's shape
result_broadcast_3 = arr1 + arr4
print("arr1 + arr4:")
print(result_broadcast_3)

# Example 4: Incompatible shapes for broadcasting
# Attempting to add arr1 (2,3) to an array of shape (4,)
# This would raise an error if uncommented:
# incompatible_arr = np.array([1, 2, 3, 4])
# try:
#     arr1 + incompatible_arr
# except ValueError as e:
#     print(f"Incompatible shapes for broadcasting: {e}")

arr1 + arr2:
[[11 22 33]
 [14 25 36]]
arr1 + arr3:
[[101 102 103]
 [204 205 206]]
arr1 + arr4:
[[ 8  9 10]
 [11 12 13]]


### Array Compatibility

In [20]:
# For element-wise operations, arrays must have compatible shapes.
# This means either their shapes are identical, or one array's shape can be broadcasted to match the other.

# Compatible: Identical shapes
comp_arr1 = np.array([[10, 20], [30, 40]])
comp_arr2 = np.array([[1, 2], [3, 4]])
print("comp_arr1 + comp_arr2 (identical shapes):")
print(comp_arr1 + comp_arr2)

# Compatible: Broadcasting (as shown above with arr1+arr2, arr1+arr3, arr1+arr4)

# Incompatible Example (for clarity, this would raise an error if uncommented)
# print("\nIncompatible example (would raise ValueError if run):")
# incompatible_op_arr1 = np.array([[1, 2], [3, 4]]) # Shape (2,2)
# incompatible_op_arr2 = np.array([10, 20, 30])    # Shape (3,)
# try:
#     incompatible_op_arr1 + incompatible_op_arr2
# except ValueError as e:
#     print(f"  Error: {e}")
#     print("  The trailing dimensions are not compatible for broadcasting.")

comp_arr1 + comp_arr2 (identical shapes):
[[11 22]
 [33 44]]
