In [1]:
import numpy as np

data = np.array([1, 4, 9, -16, 25])
print("Original:", data)

# Square root (handling only positive)
print("Sqrt:", np.sqrt(np.abs(data)))

# Logarithm
print("Log:", np.log(np.array([1, np.e, np.e**2])))

# Exponential
print("Exp:", np.exp(np.array([0, 1, 2])))

# Trigonometric
angles = np.array([0, np.pi/4, np.pi/2])
print("Sin:", np.sin(angles))
print("Cos:", np.cos(angles))

# Absolute value
print("Abs:", np.abs(data))

# Multi-dimensional example
matrix = np.array([[-1, -2], [3, 4]])
print("Matrix Abs:\n", np.abs(matrix))
print("Matrix Exp:\n", np.exp(matrix))

Original: [  1   4   9 -16  25]
Sqrt: [1. 2. 3. 4. 5.]
Log: [0. 1. 2.]
Exp: [1.         2.71828183 7.3890561 ]
Sin: [0.         0.70710678 1.        ]
Cos: [1.00000000e+00 7.07106781e-01 6.12323400e-17]
Abs: [ 1  4  9 16 25]
Matrix Abs:
 [[1 2]
 [3 4]]
Matrix Exp:
 [[ 0.36787944  0.13533528]
 [20.08553692 54.59815003]]


In [2]:


arr = np.array([10, 20, 30, 40, 50])
print(f"Sum: {np.sum(arr)}")
print(f"Mean: {np.mean(arr)}")
print(f"Median: {np.median(arr)}")
print(f"Min: {np.min(arr)}")
print(f"Max: {np.max(arr)}")
print(f"Std Dev: {np.std(arr):.2f}")
print(f"Variance: {np.var(arr):.2f}")

# Percentiles and Quantiles
print(f"75th Percentile: {np.percentile(arr, 75)}")
print(f"0.5 Quantile: {np.quantile(arr, 0.5)}")

# Correlation and Covariance
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 4, 5])
print("Correlation Matrix:\n", np.corrcoef(x, y))
print("Covariance Matrix:\n", np.cov(x, y))

Sum: 150
Mean: 30.0
Median: 30.0
Min: 10
Max: 50
Std Dev: 14.14
Variance: 200.00
75th Percentile: 40.0
0.5 Quantile: 30.0
Correlation Matrix:
 [[1.         0.77459667]
 [0.77459667 1.        ]]
Covariance Matrix:
 [[2.5 1.5]
 [1.5 1.5]]


In [4]:


arr = np.array([10, 50, 20, 50, 30])

# np.where
print("Indices where > 25:", np.where(arr > 25))
print("Value replacement:", np.where(arr > 25, "High", "Low"))

# np.argmax and np.argmin
print("Index of max:", np.argmax(arr))
print("Index of min:", np.argmin(arr))

# np.nonzero
sparse_arr = np.array([1, 0, 2, 0, 3])
print("Indices of non-zero elements:", np.nonzero(sparse_arr))

# 2D Example
matrix = np.array([[0, 1], [1, 0]])
print("2D Nonzero indices:\n", np.nonzero(matrix))

Indices where > 25: (array([1, 3, 4]),)
Value replacement: ['Low' 'High' 'Low' 'High' 'High']
Index of max: 1
Index of min: 0
Indices of non-zero elements: (array([0, 2, 4]),)
2D Nonzero indices:
 (array([0, 1]), array([1, 0]))
